widget_group_11/forums/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView, Redirection

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('posts/<int:pk>/details/', PostDetailView.as_view(), name='post_detail'),
    path('posts/add/', AddPostView.as_view(), name='add_post'),
    path('posts/add/redirect/', Redirection.as_view(), name='redirect'),
]

app_name = "widget_group_11"

widget_group_11/homepage/urls.py
from django.urls import path

from .views import UserListView, UserDetailView, UserCreateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('homepage/', UserListView.as_view(), name='user-list'),
    path('users/<int:pk>/details', UserDetailView.as_view(), name='user-detail'),
    path('users/add/', UserCreateView.as_view(), name='user-create')
]+ static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "widget_group_11"

widget_group_11/widget_group_11/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace="home")),
    path('homepage/', include('homepage.urls', namespace="homepage")),
    path('forums/', include('forums.urls', namespace="forums")),
    path('announcements/', include('announcements.urls', namespace="announcements")),
    path('assignments/', include('assignments.urls', namespace="assignments")),
    path('admin/', admin.site.urls),
]

widget_group_11/homepage/models.py
from django.db import models
from django.urls import reverse


class WidgetUser(models.Model):
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    id_num = models.CharField(max_length=7)
    email = models.EmailField(max_length=50)
    profile_image = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    department = models.ForeignKey(
        'Department',
        on_delete=models.CASCADE,
        related_name='department'
    )

    def __str__(self):
        return '{}, {} {}'.format(self.last_name, self.first_name, self.middle_name)

    def get_absolute_url(self):
        return reverse('homepage:user-list')


class Department(models.Model):
    dept_name = models.CharField(max_length=100)
    home_unit = models.CharField(max_length=100)

    def __str__(self):
        return '{}, {}'.format(self.dept_name, self.home_unit)

widget_group_11/homepage/forms.py
from django import forms


class UserForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    middle_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    id_num = forms.CharField(max_length=7)
    email = forms.EmailField(max_length=50)

widget_group_11/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .models import WidgetUser
from .forms import UserForm


class UserListView(ListView):
    model = WidgetUser


class UserDetailView(DetailView):
    model = WidgetUser


class UserCreateView(CreateView):
    model = WidgetUser
    template_name = 'homepage/widgetuser_create.html'
    fields = '__all__'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        form.fields['middle_name'].widget.attrs.update({'class': 'form-control'})
        form.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        form.fields['id_num'].widget.attrs.update({'class': 'form-control'})
        form.fields['email'].widget.attrs.update({'class': 'form-control'})
        form.fields['profile_image'].widget.attrs.update({'class': 'form-control'})
        form.fields['department'].widget.attrs.update({'class': 'form-control'})
        return form

widget_group_11/homepage/templates/homepage/widgetuser_create.html
{% extends 'base.html' %}
{% load static %}
{% block menu %}
<hr>
<ul class="nav nav-pills flex-column mb-auto">
   <li class="nav-item">
      <a href="../../" class="nav-link text-white" aria-current="page">🏠 Home</a>
   </li>
</ul>
<hr>
{% endblock %}
{% block body %}

<div class="container">
   <div class="row">
      <div class="col-10 offset-1">
         <h1>Add Widget User</h1>
         <form action="{% url 'homepage:user-create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
               <label for="{{ form.last_name.id_for_label }}">Last Name</label>
               {{ form.last_name }} 
               <label for="{{ form.first_name.id_for_label }}">First Name</label>
               {{ form.first_name }} 
               <label for="{{ form.middle_name.id_for_label }}">Middle Name</label>
                  {{ form.middle_name }}
               <label for="{{ form.id_num.id_for_label }}">ID #</label>
               {{ form.id_num }} 
               <label for="{{ form.email.id_for_label }}">Email</label>
               {{ form.email }}
               <label for="{{ form.department.id_for_label }}">Department Name</label>
               {{ form.department }} 
               <label for="{{ form.profile_image.id_for_label }}">Profile Image</label>
               {{ form.profile_image }}
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Save New User</button>
         </form>
      </div>
      <div class="col-1"></div>
   </div>
</div>

{% endblock %}

widget_group_11/homepage/templates/homepage/widgetuser_detail.html
{% extends 'base.html' %}
{% load static %}
{% block menu %}
<hr>
<ul class="nav nav-pills flex-column mb-auto">
   <li class="nav-item">
      <a href="../../" class="nav-link text-white" aria-current="page">🏠 Home</a>
   </li>
</ul>
<hr>
{% endblock %}
{% block body %}
<div class="col-3 text-center">
	{% if object.profile_image.url is not null %}
    <img src="{{ object.profile_image.url }}" width="160" height="160">
	{% else %}
    <img src="{% static 'img/default.png' %}" width="160" height="160">
    {% endif %}
   <br><br>
   <p><b>{{ object.last_name }}, {{ object.first_name }} {{ object.middle_name }} </b></p>
</div>
<div class="col-8">
   <table class="table">
      <thead>
         <tr>
            <th scope="col">ID #</th>
            <th scope="col">Email Address</th>
            <th scope="col">Department Name</th>
            <th scope="col">Home Unit</th>
         </tr>
      </thead>
      <tbody>
         <tr>
            <td>{{ object.id_num }}</td>
            <td>{{ object.email }}</td>
            <td>{{ object.department.dept_name }}</td>
            <td>{{ object.department.home_unit }}</td>
         </tr>
      </tbody>
   </table>
</div>
<div class="col-1">
</div>

{% endblock %}

widget_group_11/homepage/templates/homepage/widgetuser_list.html
{% extends 'base.html' %}
{% load static %}
{% block menu %}
<hr>
<ul class="nav nav-pills flex-column mb-auto">
   <li class="nav-item">
      <a href="./" class="nav-link active" aria-current="page">🏠 Home</a>
   </li>
</ul>
<hr>
{% endblock %}
{% block body %}
<div class="col-11 offset-1">
   <h1> Welcome to Widget!</h1>
   <ol>
      {% for object in object_list|dictsort:"last_name" %}
      <li>
         <a href="{% url 'homepage:user-detail' pk=object.pk %}">
         {{ object.last_name }}, {{ object.first_name }} {{ object.middle_name }} 
         </a>
      </li>
      {% endfor%}
   </ol>
   <form action="{% url 'homepage:user-create' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Add Widget User</button>
   </form>
</div>
{% endblock %}