widget_group_11/forums/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView, Redirection

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('posts/<int:pk>/details/', PostDetailView.as_view(), name='post_detail'),
    path('posts/add/', AddPostView.as_view(), name='add_post'),
    path('posts/add/redirect/', Redirection.as_view(), name='redirect'),
]

app_name = "widget_group_11"

widget_group_11/widget_group_11/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace="home")),
    path('homepage/', include('homepage.urls', namespace="homepage")),
    path('forums/', include('forums.urls', namespace="forums")),
    path('announcements/', include('announcements.urls', namespace="announcements")),
    path('assignments/', include('assignments.urls', namespace="assignments")),
    path('admin/', admin.site.urls),
]

widget_group_11/forums/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from homepage.models import WidgetUser

# Create your models here.

class Post(models.Model):
    post_title = models.CharField(max_length=50)
    post_body = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=datetime.now)
    author = models.ForeignKey(WidgetUser, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('postdetailview', args=[str(self.id)])

    def save(self, *args, **kwargs):
        if not self.pub_date:
            self.pub_date = datetime.now
        return super().save(*args, **kwargs)

class Reply(models.Model):
    reply_body = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=datetime.now)
    author = models.ForeignKey(WidgetUser, on_delete=models.CASCADE, default='')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default='')

    class Meta:
        verbose_name_plural = "Replies"

    def where_posted(self):
        return self.post

widget_group_11/forums/forms.py
from django import forms

from .models import Post

class AddForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('post_title', 'post_body', 'author')

widget_group_11/forums/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.views import View
from django.views.generic import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from .forms import AddForm

from .models import Post, Reply

# Create your views here.
class HomePageView(ListView):
    model = Post
    template_name='forums/index.html'
    ordering =['-pub_date']

class PostDetailView(DetailView):
    model = Post
    template_name = 'forums/post-detail.html'
    context_object_name = 'post'

class AddPostView(FormView):
    template_name = 'forums/add-post.html'
    form_class = AddForm
    success_url = 'redirect/'

    def form_valid(self,form):
        form.save()
        return super().form_valid(form)

class Redirection(RedirectView):

    pattern_name = 'forums:index'

widget_group_11/forums/templates/forums/add-post.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>

{% block body %}
  <link rel="stylesheet" type="text/css" href="{% static 'forums/style.css' %}">
    <h1>New Forum Post</h1>
    <hr>
  </body>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value="Save Post">
  </form>
{% endblock %}

widget_group_11/forums/templates/forums/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>

{% block body %}
  <link rel="stylesheet" type="text/css" href="{% static 'forums/style.css' %}">
    <h1>Welcome to Widget’s Forum!</h1>
    {% if post_list %}
        <ul>
        {% for post in post_list %}
            <li>
              <h2>
                <a href="{% url 'forums:post_detail' post.pk %}">
                {{post.post_title}} by {{post.author.first_name}} {{post.author.last_name}}
              </a>
              </h2>
              <h3>dated {{post.pub_date}}:</h3>
              <p>{{post.post_body}}</p>
              <ul>
              {% for reply in post.reply_set.all %}
                <li>
                  Reply by {{reply.author.first_name}} {{reply.author.last_name}} {{reply.pubdate}}:<br>
                  {{reply.reply_body}}
                </li>
              {% endfor %}
              </ul>
            <hr>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
    <form action="{% url 'forums:add_post' %}">
      <input type="submit" value="New Forum Post" />
    </form>
{% endblock %}

widget_group_11/forums/templates/forums/post-detail.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>

{% block body %}
  <link rel="stylesheet" type="text/css" href="{% static 'forums/style.css' %}">
  <form action="{% url 'forums:index' %}">
    <input type="submit" value="Back to Forums" />
  </form>
  <br>
  <span class="border border-secondary"><h1>{{post.post_title}}</h1></span>
  <h3>by {{post.author}} {{post.pub_date}}</h3>
  <p>{{post.post_body}}</p>
  <hr>
  <ul>
  {% for reply in post.reply_set.all %}
    <li>
      {{reply.author.first_name}} {{reply.author.last_name}}, {{reply.pubdate}}:<br>
      {{reply.reply_body}}
    </li>
  {% endfor %}
  </ul>
  {% endblock %}