widget_group_11/announcements/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path("<int:announcement_id>/details/", views.detail, name="detail"),
    path("add/", views.add_announcement, name="add_announcement"),
]

app_name = "widget_group_11"

widget_group_11/forums/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView, Redirection

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('posts/<int:pk>/details/', PostDetailView.as_view(), name='post_detail'),
    path('posts/add/', AddPostView.as_view(), name='add_post'),
    path('posts/add/redirect/', Redirection.as_view(), name='redirect'),
]

app_name = "widget_group_11"

widget_group_11/widget_group_11/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace="home")),
    path('homepage/', include('homepage.urls', namespace="homepage")),
    path('forums/', include('forums.urls', namespace="forums")),
    path('announcements/', include('announcements.urls', namespace="announcements")),
    path('assignments/', include('assignments.urls', namespace="assignments")),
    path('admin/', admin.site.urls),
]

widget_group_11/announcements/models.py
from django.db import models
from homepage.models import WidgetUser

# Create your models here.


class Announcement(models.Model):

    announcement_title = models.CharField(max_length=50)
    announcement_body = models.CharField(max_length=500)
    pub_date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(WidgetUser, on_delete=models.CASCADE, default='', related_name='author')

    def __str__(self):
        return (self.announcement_title)


class Reaction(models.Model):
    reaction_choices = [
        ("Like", "Like"),
        ("Love", "Love"),
        ("Angry", "Angry")
    ]
    announcement = models.ForeignKey(
        Announcement, on_delete=models.CASCADE, related_name='announcements')
    reaction_name = models.CharField(
        max_length=10, choices=reaction_choices, default="Like")
    tally = models.IntegerField(default=0)

    def __str__(self):
        return (self.reaction_name)

widget_group_11/announcements/forms.py
from django.forms import ModelForm
from .models import Announcement

class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        fields = [
            "announcement_title", 
            "announcement_body",
            "author"
        ]

widget_group_11/announcements/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, Http404
from django.views import View

from .forms import AnnouncementForm

from .models import Announcement, Reaction

# Create your views here.


class HomePageView(View):
    def get(self, request):
        announcement_list = Announcement.objects.order_by("-id")
        return render(request, "announcements/index.html", {"announcement_list": announcement_list})

def add_announcement(request):
    if request.method == "POST":
        announcement_form = AnnouncementForm(request.POST)
        if announcement_form.is_valid():
            announcement_form = announcement_form.save()
            return redirect("announcements:add_announcement")
    else:
        announcement_form = AnnouncementForm()
    return render(request, "announcements/forms.html", {"announcement_form": announcement_form})


def detail(request, announcement_id):
    try: 
        announcement = Announcement.objects.get(pk = announcement_id)
        reaction_list = Reaction.objects.filter(announcement_id=announcement.id)
    except Announcement.DoesNotExist:
        raise Http404("Announcement does not exist.")
    return render(request, "announcements/details.html", {"announcement": announcement, "reaction_list": reaction_list})
    

widget_group_11/announcements/templates/announcements/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href = "{% static 'announcements/style.css' %}">
        <title>Widget Group 11</title>
    </head>

    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

widget_group_11/announcements/templates/announcements/details.html
{% extends "announcements/base.html" %}

{% block content %}

<h1>{{ announcement.announcement_title }}</h1>
<h2>
    by {{announcement.author.first_name}} {{announcement.author.last_name}}, {{ announcement.pub_date|date:"d-m-Y" }}
</h2>

<a>{{announcement.announcement_body}}</a>
<ul>
    {% for reaction in reaction_list %}
    <li>
        {{reaction.reaction_name}}: {{reaction.tally}}

    </li>
    {% endfor %}
</ul>


{% load static %} 
<img src="{% static 'announcements/image.png' %}">

{% endblock %}

widget_group_11/announcements/templates/announcements/forms.html
{% extends "announcements/base.html" %}

{% block content %}
    <h1>
        New Announcement
    </h1>

    <form action = "{% url 'widget_group_11:add_announcement' %}" method="POST">
        {% csrf_token %}
        {{ announcement_form.as_p }}

        <button class="button" type="submit">Save Announcement</button>
    </form>


    <a href = "{% url 'widget_group_11:index' %}">
        Return to announcements page
   </a>


{% endblock %}

widget_group_11/announcements/templates/announcements/index.html
{% extends "announcements/base.html" %}

{% block content %}
<h1>Announcement Board</h1>
<p>Important announcements:</p>

{% if announcement_list %}
<ul>
    {% for announcement in announcement_list %}
    <li>
        <a href="{% url 'widget_group_11:detail' announcement.id %}">
            {{announcement.announcement_title}} by
            {{announcement.author.first_name}} {{announcement.author.last_name}}
            dated {{ announcement.pub_date|date:"d-m-Y" }}
        </a>

    </li>
    {% endfor %}
</ul>
{% else %}
<p>No announcements are available</p>
{% endif %} 

<a href = "{% url 'widget_group_11:add_announcement' %}">
     New Announcement
</a>


{% endblock %}